---
title: "Statistical methods for assessing agreement between two methods of clinical measurement"
author: "Oxford IHTM Class 2024"
date: "`r Sys.Date()`"
output: 
  rmarkdown::html_document:
    toc: true
    keep_md: true
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)

library(ggplot2)
ba = read.table("https://raw.githubusercontent.com/OxfordIHTM/teaching_datasets/main/ba.dat",header=TRUE)

average = rowMeans(ba)
ba$average = average

#Mean differences 
difference <- ba$Wright - ba$Mini
ba$difference = difference
mean_difference = mean(difference)

#Confidence interval
lower <- mean_difference - 1.96*sd(ba$difference)
upper <- mean_difference + 1.96*sd(ba$difference)
```

# Task 4: Report 

## 1. Table of the mean and difference of per subject measurements made by the Wright and the Mini-Wright



## 2. Bland and Altman plot
```{r plot}
plot = ggplot(ba, aes(x = average, y = difference)) +
  geom_point() +
  geom_hline(yintercept = mean_difference) +
  geom_hline(yintercept = lower, color = "red", linetype="dashed") +
  geom_hline(yintercept = upper, color = "red", linetype="dashed") +
  ylab("PEFR (l/min) Mini Wright meter - Wright meter ") +
  xlab("PEFR (l/min) Mini Wright meter + Wright meter / 2")

plot 
```

## 3. Discussion of the findings with regard to the agreement between the Wright and Mini-Wright tools.

